
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: ror_dev_db
  username: pgadminruby
  password: password
  host: localhost

test:
  <<: *default
  database: ror_test_db
  username: pgadminruby
  password: password
  host: localhost

production:
  <<: *default
  database: ror_production_db
  username: pgadminruby
  password: password
  host: localhost
